<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan__lokasi_kumuh extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kawasan__lokasi_kumuh_model');
    } 

    /*
     * Listing of kawasan__lokasi_kumuh
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('kawasan__lokasi_kumuh/index?');
        $config['total_rows'] = $this->Kawasan__lokasi_kumuh_model->get_all_kawasan__lokasi_kumuh_count();
        $this->pagination->initialize($config);

        $data['kawasan__lokasi_kumuh'] = $this->Kawasan__lokasi_kumuh_model->get_all_kawasan__lokasi_kumuh($params);
        
        $data['_view'] = 'kawasan__lokasi_kumuh/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kawasan__lokasi_kumuh
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('lokasi','Lokasi','required|max_length[100]');
		$this->form_validation->set_rules('luas','Luas','required|numeric');
		$this->form_validation->set_rules('rt_rw','Rt Rw','required|max_length[50]');
		$this->form_validation->set_rules('village_id','Village Id','required|integer');
		$this->form_validation->set_rules('lintang','Lintang','required|numeric');
		$this->form_validation->set_rules('bujur','Bujur','required|numeric');
		$this->form_validation->set_rules('tingkat_kumuh','Tingkat Kumuh','required|max_length[25]');
		$this->form_validation->set_rules('id_sk','Id Sk','required|integer');
		$this->form_validation->set_rules('last_update','Last Update','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'village_id' => $this->input->post('village_id'),
				'id_sk' => $this->input->post('id_sk'),
				'lokasi' => $this->input->post('lokasi'),
				'luas' => $this->input->post('luas'),
				'rt_rw' => $this->input->post('rt_rw'),
				'lintang' => $this->input->post('lintang'),
				'bujur' => $this->input->post('bujur'),
				'tingkat_kumuh' => $this->input->post('tingkat_kumuh'),
				'last_update' => $this->input->post('last_update'),
            );
            
            $kawasan__lokasi_kumuh_id = $this->Kawasan__lokasi_kumuh_model->add_kawasan__lokasi_kumuh($params);
            redirect('kawasan__lokasi_kumuh/index');
        }
        else
        {
			$this->load->model('Reg__village_model');
			$data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

			$this->load->model('Kawasan__surat_keterangan_kumuh_model');
			$data['all_kawasan__surat_keterangan_kumuh'] = $this->Kawasan__surat_keterangan_kumuh_model->get_all_kawasan__surat_keterangan_kumuh();
            
            $data['_view'] = 'kawasan__lokasi_kumuh/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kawasan__lokasi_kumuh
     */
    function edit($id_lokasi)
    {   
        // check if the kawasan__lokasi_kumuh exists before trying to edit it
        $data['kawasan__lokasi_kumuh'] = $this->Kawasan__lokasi_kumuh_model->get_kawasan__lokasi_kumuh($id_lokasi);
        
        if(isset($data['kawasan__lokasi_kumuh']['id_lokasi']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('lokasi','Lokasi','required|max_length[100]');
			$this->form_validation->set_rules('luas','Luas','required|numeric');
			$this->form_validation->set_rules('rt_rw','Rt Rw','required|max_length[50]');
			$this->form_validation->set_rules('village_id','Village Id','required|integer');
			$this->form_validation->set_rules('lintang','Lintang','required|numeric');
			$this->form_validation->set_rules('bujur','Bujur','required|numeric');
			$this->form_validation->set_rules('tingkat_kumuh','Tingkat Kumuh','required|max_length[25]');
			$this->form_validation->set_rules('id_sk','Id Sk','required|integer');
			$this->form_validation->set_rules('last_update','Last Update','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'village_id' => $this->input->post('village_id'),
					'id_sk' => $this->input->post('id_sk'),
					'lokasi' => $this->input->post('lokasi'),
					'luas' => $this->input->post('luas'),
					'rt_rw' => $this->input->post('rt_rw'),
					'lintang' => $this->input->post('lintang'),
					'bujur' => $this->input->post('bujur'),
					'tingkat_kumuh' => $this->input->post('tingkat_kumuh'),
					'last_update' => $this->input->post('last_update'),
                );

                $this->Kawasan__lokasi_kumuh_model->update_kawasan__lokasi_kumuh($id_lokasi,$params);            
                redirect('kawasan__lokasi_kumuh/index');
            }
            else
            {
				$this->load->model('Reg__village_model');
				$data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

				$this->load->model('Kawasan__surat_keterangan_kumuh_model');
				$data['all_kawasan__surat_keterangan_kumuh'] = $this->Kawasan__surat_keterangan_kumuh_model->get_all_kawasan__surat_keterangan_kumuh();

                $data['_view'] = 'kawasan__lokasi_kumuh/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kawasan__lokasi_kumuh you are trying to edit does not exist.');
    } 

    /*
     * Deleting kawasan__lokasi_kumuh
     */
    function remove($id_lokasi)
    {
        $kawasan__lokasi_kumuh = $this->Kawasan__lokasi_kumuh_model->get_kawasan__lokasi_kumuh($id_lokasi);

        // check if the kawasan__lokasi_kumuh exists before trying to delete it
        if(isset($kawasan__lokasi_kumuh['id_lokasi']))
        {
            $this->Kawasan__lokasi_kumuh_model->delete_kawasan__lokasi_kumuh($id_lokasi);
            redirect('kawasan__lokasi_kumuh/index');
        }
        else
            show_error('The kawasan__lokasi_kumuh you are trying to delete does not exist.');
    }
    
}
