<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan__surat_keterangan_kumuh extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kawasan__surat_keterangan_kumuh_model');
    } 

    /*
     * Listing of kawasan__surat_keterangan_kumuh
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('kawasan__surat_keterangan_kumuh/index?');
        $config['total_rows'] = $this->Kawasan__surat_keterangan_kumuh_model->get_all_kawasan__surat_keterangan_kumuh_count();
        $this->pagination->initialize($config);

        $data['kawasan__surat_keterangan_kumuh'] = $this->Kawasan__surat_keterangan_kumuh_model->get_all_kawasan__surat_keterangan_kumuh($params);
        
        $data['_view'] = 'kawasan__surat_keterangan_kumuh/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kawasan__surat_keterangan_kumuh
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('sk','Sk','required|max_length[100]');
		$this->form_validation->set_rules('tahun','Tahun','required|integer');
		$this->form_validation->set_rules('last_update','Last Update','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'regency_id' => $this->input->post('regency_id'),
				'sk' => $this->input->post('sk'),
				'tahun' => $this->input->post('tahun'),
				'last_update' => $this->input->post('last_update'),
            );
            
            $kawasan__surat_keterangan_kumuh_id = $this->Kawasan__surat_keterangan_kumuh_model->add_kawasan__surat_keterangan_kumuh($params);
            redirect('kawasan__surat_keterangan_kumuh/index');
        }
        else
        {
			$this->load->model('Reg__regency_model');
			$data['all_reg__regencies'] = $this->Reg__regency_model->get_all_reg__regencies();
            
            $data['_view'] = 'kawasan__surat_keterangan_kumuh/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kawasan__surat_keterangan_kumuh
     */
    function edit($id_sk)
    {   
        // check if the kawasan__surat_keterangan_kumuh exists before trying to edit it
        $data['kawasan__surat_keterangan_kumuh'] = $this->Kawasan__surat_keterangan_kumuh_model->get_kawasan__surat_keterangan_kumuh($id_sk);
        
        if(isset($data['kawasan__surat_keterangan_kumuh']['id_sk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('sk','Sk','required|max_length[100]');
			$this->form_validation->set_rules('tahun','Tahun','required|integer');
			$this->form_validation->set_rules('last_update','Last Update','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'regency_id' => $this->input->post('regency_id'),
					'sk' => $this->input->post('sk'),
					'tahun' => $this->input->post('tahun'),
					'last_update' => $this->input->post('last_update'),
                );

                $this->Kawasan__surat_keterangan_kumuh_model->update_kawasan__surat_keterangan_kumuh($id_sk,$params);            
                redirect('kawasan__surat_keterangan_kumuh/index');
            }
            else
            {
				$this->load->model('Reg__regency_model');
				$data['all_reg__regencies'] = $this->Reg__regency_model->get_all_reg__regencies();

                $data['_view'] = 'kawasan__surat_keterangan_kumuh/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kawasan__surat_keterangan_kumuh you are trying to edit does not exist.');
    } 

    /*
     * Deleting kawasan__surat_keterangan_kumuh
     */
    function remove($id_sk)
    {
        $kawasan__surat_keterangan_kumuh = $this->Kawasan__surat_keterangan_kumuh_model->get_kawasan__surat_keterangan_kumuh($id_sk);

        // check if the kawasan__surat_keterangan_kumuh exists before trying to delete it
        if(isset($kawasan__surat_keterangan_kumuh['id_sk']))
        {
            $this->Kawasan__surat_keterangan_kumuh_model->delete_kawasan__surat_keterangan_kumuh($id_sk);
            redirect('kawasan__surat_keterangan_kumuh/index');
        }
        else
            show_error('The kawasan__surat_keterangan_kumuh you are trying to delete does not exist.');
    }
    
}
