<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan__penanganan_lokasi_kumuh extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kawasan__penanganan_lokasi_kumuh_model');
    } 

    /*
     * Listing of kawasan__penanganan_lokasi_kumuh
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('kawasan__penanganan_lokasi_kumuh/index?');
        $config['total_rows'] = $this->Kawasan__penanganan_lokasi_kumuh_model->get_all_kawasan__penanganan_lokasi_kumuh_count();
        $this->pagination->initialize($config);

        $data['kawasan__penanganan_lokasi_kumuh'] = $this->Kawasan__penanganan_lokasi_kumuh_model->get_all_kawasan__penanganan_lokasi_kumuh($params);
        
        $data['_view'] = 'kawasan__penanganan_lokasi_kumuh/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kawasan__penanganan_lokasi_kumuh
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nominal','Nominal','required|integer');
		$this->form_validation->set_rules('kegiatan','Kegiatan','required|max_length[80]');
		$this->form_validation->set_rules('tahun','Tahun','required|integer');
		$this->form_validation->set_rules('sumber_dana','Sumber Dana','required|max_length[20]');
		$this->form_validation->set_rules('luas_tertangani','Luas Tertangani','required|numeric');
		$this->form_validation->set_rules('lng','Lng','required|max_length[20]');
		$this->form_validation->set_rules('lat','Lat','required|max_length[20]');
		$this->form_validation->set_rules('last_update','Last Update','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_lokasi' => $this->input->post('id_lokasi'),
				'nominal' => $this->input->post('nominal'),
				'kegiatan' => $this->input->post('kegiatan'),
				'tahun' => $this->input->post('tahun'),
				'sumber_dana' => $this->input->post('sumber_dana'),
				'luas_tertangani' => $this->input->post('luas_tertangani'),
				'lng' => $this->input->post('lng'),
				'lat' => $this->input->post('lat'),
				'last_update' => $this->input->post('last_update'),
            );
            
            $kawasan__penanganan_lokasi_kumuh_id = $this->Kawasan__penanganan_lokasi_kumuh_model->add_kawasan__penanganan_lokasi_kumuh($params);
            redirect('kawasan__penanganan_lokasi_kumuh/index');
        }
        else
        {
			$this->load->model('Kawasan__lokasi_kumuh_model');
			$data['all_kawasan__lokasi_kumuh'] = $this->Kawasan__lokasi_kumuh_model->get_all_kawasan__lokasi_kumuh();
            
            $data['_view'] = 'kawasan__penanganan_lokasi_kumuh/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kawasan__penanganan_lokasi_kumuh
     */
    function edit($id_penanganan)
    {   
        // check if the kawasan__penanganan_lokasi_kumuh exists before trying to edit it
        $data['kawasan__penanganan_lokasi_kumuh'] = $this->Kawasan__penanganan_lokasi_kumuh_model->get_kawasan__penanganan_lokasi_kumuh($id_penanganan);
        
        if(isset($data['kawasan__penanganan_lokasi_kumuh']['id_penanganan']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nominal','Nominal','required|integer');
			$this->form_validation->set_rules('kegiatan','Kegiatan','required|max_length[80]');
			$this->form_validation->set_rules('tahun','Tahun','required|integer');
			$this->form_validation->set_rules('sumber_dana','Sumber Dana','required|max_length[20]');
			$this->form_validation->set_rules('luas_tertangani','Luas Tertangani','required|numeric');
			$this->form_validation->set_rules('lng','Lng','required|max_length[20]');
			$this->form_validation->set_rules('lat','Lat','required|max_length[20]');
			$this->form_validation->set_rules('last_update','Last Update','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_lokasi' => $this->input->post('id_lokasi'),
					'nominal' => $this->input->post('nominal'),
					'kegiatan' => $this->input->post('kegiatan'),
					'tahun' => $this->input->post('tahun'),
					'sumber_dana' => $this->input->post('sumber_dana'),
					'luas_tertangani' => $this->input->post('luas_tertangani'),
					'lng' => $this->input->post('lng'),
					'lat' => $this->input->post('lat'),
					'last_update' => $this->input->post('last_update'),
                );

                $this->Kawasan__penanganan_lokasi_kumuh_model->update_kawasan__penanganan_lokasi_kumuh($id_penanganan,$params);            
                redirect('kawasan__penanganan_lokasi_kumuh/index');
            }
            else
            {
				$this->load->model('Kawasan__lokasi_kumuh_model');
				$data['all_kawasan__lokasi_kumuh'] = $this->Kawasan__lokasi_kumuh_model->get_all_kawasan__lokasi_kumuh();

                $data['_view'] = 'kawasan__penanganan_lokasi_kumuh/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kawasan__penanganan_lokasi_kumuh you are trying to edit does not exist.');
    } 

    /*
     * Deleting kawasan__penanganan_lokasi_kumuh
     */
    function remove($id_penanganan)
    {
        $kawasan__penanganan_lokasi_kumuh = $this->Kawasan__penanganan_lokasi_kumuh_model->get_kawasan__penanganan_lokasi_kumuh($id_penanganan);

        // check if the kawasan__penanganan_lokasi_kumuh exists before trying to delete it
        if(isset($kawasan__penanganan_lokasi_kumuh['id_penanganan']))
        {
            $this->Kawasan__penanganan_lokasi_kumuh_model->delete_kawasan__penanganan_lokasi_kumuh($id_penanganan);
            redirect('kawasan__penanganan_lokasi_kumuh/index');
        }
        else
            show_error('The kawasan__penanganan_lokasi_kumuh you are trying to delete does not exist.');
    }
    
}
