<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Perumahan__kepemilikan_rumah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan__kepemilikan_rumah_model');
    }

    /*
     * Listing of perumahan__kepemilikan_rumah
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('perumahan__kepemilikan_rumah/index?');
        $config['total_rows'] = $this->Perumahan__kepemilikan_rumah_model->get_all_perumahan__kepemilikan_rumah_count();
        $this->pagination->initialize($config);

        $data['perumahan__kepemilikan_rumah'] = $this->Perumahan__kepemilikan_rumah_model->get_all_perumahan__kepemilikan_rumah($params);
        $data['title'] = "Kepemilikan Rumah";
        $data['_view'] = 'perumahan__kepemilikan_rumah/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new perumahan__kepemilikan_rumah
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('village_id', 'Village Id', 'required|integer');
        $this->form_validation->set_rules('jumlah_kk', 'Jumlah Kk', 'required|integer');
        $this->form_validation->set_rules('rumah_milik_sendiri', 'Rumah Milik Sendiri', 'required|integer');
        $this->form_validation->set_rules('rumah_sewa', 'Rumah Sewa', 'required|integer');
        $this->form_validation->set_rules('rumah_bebas_sewa', 'Rumah Bebas Sewa', 'required|integer');
        $this->form_validation->set_rules('rumah_dinas', 'Rumah Dinas', 'required|integer');
        $this->form_validation->set_rules('rumah_lainnya', 'Rumah Lainnya', 'required|integer');
        $this->form_validation->set_rules('rumah_tapak', 'Rumah Tapak', 'required|integer');
        $this->form_validation->set_rules('rumah_susun', 'Rumah Susun', 'required|integer');
        $this->form_validation->set_rules('tahun', 'Tahun', 'required|integer');
        $this->form_validation->set_rules('keterangan', 'Keterangan', 'required|max_length[100]');
        $this->form_validation->set_rules('last_update', 'Last Update', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'village_id' => $this->input->post('village_id'),
                'jumlah_kk' => $this->input->post('jumlah_kk'),
                'rumah_milik_sendiri' => $this->input->post('rumah_milik_sendiri'),
                'rumah_sewa' => $this->input->post('rumah_sewa'),
                'rumah_bebas_sewa' => $this->input->post('rumah_bebas_sewa'),
                'rumah_dinas' => $this->input->post('rumah_dinas'),
                'rumah_lainnya' => $this->input->post('rumah_lainnya'),
                'rumah_tapak' => $this->input->post('rumah_tapak'),
                'rumah_susun' => $this->input->post('rumah_susun'),
                'tahun' => $this->input->post('tahun'),
                'keterangan' => $this->input->post('keterangan'),
                'last_update' => $this->input->post('last_update'),
            );

            $perumahan__kepemilikan_rumah_id = $this->Perumahan__kepemilikan_rumah_model->add_perumahan__kepemilikan_rumah($params);
            redirect('perumahan__kepemilikan_rumah/index');
        } else {
            $this->load->model('Reg__village_model');
            $data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

            $data['_view'] = 'perumahan__kepemilikan_rumah/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a perumahan__kepemilikan_rumah
     */
    function edit($id_kepemilikan)
    {
        // check if the perumahan__kepemilikan_rumah exists before trying to edit it
        $data['perumahan__kepemilikan_rumah'] = $this->Perumahan__kepemilikan_rumah_model->get_perumahan__kepemilikan_rumah($id_kepemilikan);

        if (isset($data['perumahan__kepemilikan_rumah']['id_kepemilikan'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('village_id', 'Village Id', 'required|integer');
            $this->form_validation->set_rules('jumlah_kk', 'Jumlah Kk', 'required|integer');
            $this->form_validation->set_rules('rumah_milik_sendiri', 'Rumah Milik Sendiri', 'required|integer');
            $this->form_validation->set_rules('rumah_sewa', 'Rumah Sewa', 'required|integer');
            $this->form_validation->set_rules('rumah_bebas_sewa', 'Rumah Bebas Sewa', 'required|integer');
            $this->form_validation->set_rules('rumah_dinas', 'Rumah Dinas', 'required|integer');
            $this->form_validation->set_rules('rumah_lainnya', 'Rumah Lainnya', 'required|integer');
            $this->form_validation->set_rules('rumah_tapak', 'Rumah Tapak', 'required|integer');
            $this->form_validation->set_rules('rumah_susun', 'Rumah Susun', 'required|integer');
            $this->form_validation->set_rules('tahun', 'Tahun', 'required|integer');
            $this->form_validation->set_rules('keterangan', 'Keterangan', 'required|max_length[100]');
            $this->form_validation->set_rules('last_update', 'Last Update', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'village_id' => $this->input->post('village_id'),
                    'jumlah_kk' => $this->input->post('jumlah_kk'),
                    'rumah_milik_sendiri' => $this->input->post('rumah_milik_sendiri'),
                    'rumah_sewa' => $this->input->post('rumah_sewa'),
                    'rumah_bebas_sewa' => $this->input->post('rumah_bebas_sewa'),
                    'rumah_dinas' => $this->input->post('rumah_dinas'),
                    'rumah_lainnya' => $this->input->post('rumah_lainnya'),
                    'rumah_tapak' => $this->input->post('rumah_tapak'),
                    'rumah_susun' => $this->input->post('rumah_susun'),
                    'tahun' => $this->input->post('tahun'),
                    'keterangan' => $this->input->post('keterangan'),
                    'last_update' => $this->input->post('last_update'),
                );

                $this->Perumahan__kepemilikan_rumah_model->update_perumahan__kepemilikan_rumah($id_kepemilikan, $params);
                redirect('perumahan__kepemilikan_rumah/index');
            } else {
                $this->load->model('Reg__village_model');
                $data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

                $data['_view'] = 'perumahan__kepemilikan_rumah/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The perumahan__kepemilikan_rumah you are trying to edit does not exist.');
    }

    /*
     * Deleting perumahan__kepemilikan_rumah
     */
    function remove($id_kepemilikan)
    {
        $perumahan__kepemilikan_rumah = $this->Perumahan__kepemilikan_rumah_model->get_perumahan__kepemilikan_rumah($id_kepemilikan);

        // check if the perumahan__kepemilikan_rumah exists before trying to delete it
        if (isset($perumahan__kepemilikan_rumah['id_kepemilikan'])) {
            $this->Perumahan__kepemilikan_rumah_model->delete_perumahan__kepemilikan_rumah($id_kepemilikan);
            redirect('perumahan__kepemilikan_rumah/index');
        } else
            show_error('The perumahan__kepemilikan_rumah you are trying to delete does not exist.');
    }
}
