<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__imb extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan_dropdown__imb_model');
    } 

    /*
     * Listing of perumahan_dropdown__imb
     */
    function index()
    {
        $data['perumahan_dropdown__imb'] = $this->Perumahan_dropdown__imb_model->get_all_perumahan_dropdown__imb();
        
        $data['_view'] = 'perumahan_dropdown__imb/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perumahan_dropdown__imb
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'imb' => $this->input->post('imb'),
            );
            
            $perumahan_dropdown__imb_id = $this->Perumahan_dropdown__imb_model->add_perumahan_dropdown__imb($params);
            redirect('perumahan_dropdown__imb/index');
        }
        else
        {            
            $data['_view'] = 'perumahan_dropdown__imb/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perumahan_dropdown__imb
     */
    function edit($id_imb)
    {   
        // check if the perumahan_dropdown__imb exists before trying to edit it
        $data['perumahan_dropdown__imb'] = $this->Perumahan_dropdown__imb_model->get_perumahan_dropdown__imb($id_imb);
        
        if(isset($data['perumahan_dropdown__imb']['id_imb']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'imb' => $this->input->post('imb'),
                );

                $this->Perumahan_dropdown__imb_model->update_perumahan_dropdown__imb($id_imb,$params);            
                redirect('perumahan_dropdown__imb/index');
            }
            else
            {
                $data['_view'] = 'perumahan_dropdown__imb/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perumahan_dropdown__imb you are trying to edit does not exist.');
    } 

    /*
     * Deleting perumahan_dropdown__imb
     */
    function remove($id_imb)
    {
        $perumahan_dropdown__imb = $this->Perumahan_dropdown__imb_model->get_perumahan_dropdown__imb($id_imb);

        // check if the perumahan_dropdown__imb exists before trying to delete it
        if(isset($perumahan_dropdown__imb['id_imb']))
        {
            $this->Perumahan_dropdown__imb_model->delete_perumahan_dropdown__imb($id_imb);
            redirect('perumahan_dropdown__imb/index');
        }
        else
            show_error('The perumahan_dropdown__imb you are trying to delete does not exist.');
    }
    
}
