<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Perumahan__pembangunan_rumah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan__pembangunan_rumah_model');
    }

    /*
     * Listing of perumahan__pembangunan_rumah
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('perumahan__pembangunan_rumah/index?');
        $config['total_rows'] = $this->Perumahan__pembangunan_rumah_model->get_all_perumahan__pembangunan_rumah_count();
        $this->pagination->initialize($config);

        $data['perumahan__pembangunan_rumah'] = $this->Perumahan__pembangunan_rumah_model->get_all_perumahan__pembangunan_rumah($params);
        $data['title'] = "Pembangunan Rumah";
        $data['_view'] = 'perumahan__pembangunan_rumah/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new perumahan__pembangunan_rumah
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('unit', 'Unit', 'required|integer');
        $this->form_validation->set_rules('tahun', 'Tahun', 'required|integer');
        $this->form_validation->set_rules('keterangan', 'Keterangan', 'required|max_length[100]');
        $this->form_validation->set_rules('last_update', 'Last Update', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                // 'village_id' => $this->input->post('village_id'),
                'village_id' => $this->input->post('kelurahan'),
                'id_mbr' => $this->input->post('id_mbr'),
                'id_imb' => $this->input->post('id_imb'),
                'id_pelaksana' => $this->input->post('id_pelaksana'),
                'unit' => $this->input->post('unit'),
                'tahun' => $this->input->post('tahun'),
                'keterangan' => $this->input->post('keterangan'),

            );

            $perumahan__pembangunan_rumah_id = $this->Perumahan__pembangunan_rumah_model->add_perumahan__pembangunan_rumah($params);
            redirect('perumahan__pembangunan_rumah/index');
        } else {
            $this->load->model('Reg__village_model');
            $data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

            $this->load->model('Reg__regency_model');
            $data['all_reg__regencies'] = $this->Reg__regency_model->get_all_reg__regencies();

            $this->load->model('Perumahan_dropdown__mbr_model');
            $data['all_perumahan_dropdown__mbr'] = $this->Perumahan_dropdown__mbr_model->get_all_perumahan_dropdown__mbr();

            $this->load->model('Perumahan_dropdown__imb_model');
            $data['all_perumahan_dropdown__imb'] = $this->Perumahan_dropdown__imb_model->get_all_perumahan_dropdown__imb();

            $this->load->model('Perumahan_dropdown__pelaksana_model');
            $data['all_perumahan_dropdown__pelaksana'] = $this->Perumahan_dropdown__pelaksana_model->get_all_perumahan_dropdown__pelaksana();
            $data['title'] = "Tambah Pembangunan Rumah";
            $data['_view'] = 'perumahan__pembangunan_rumah/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a perumahan__pembangunan_rumah
     */
    function edit($id_pembangunan)
    {
        // check if the perumahan__pembangunan_rumah exists before trying to edit it
        $data['perumahan__pembangunan_rumah'] = $this->Perumahan__pembangunan_rumah_model->get_perumahan__pembangunan_rumah($id_pembangunan);

        if (isset($data['perumahan__pembangunan_rumah']['id_pembangunan'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('unit', 'Unit', 'required|integer');
            $this->form_validation->set_rules('tahun', 'Tahun', 'required|integer');
            $this->form_validation->set_rules('keterangan', 'Keterangan', 'required|max_length[100]');
            $this->form_validation->set_rules('last_update', 'Last Update', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'village_id' => $this->input->post('village_id'),
                    'id_mbr' => $this->input->post('id_mbr'),
                    'id_imb' => $this->input->post('id_imb'),
                    'id_pelaksana' => $this->input->post('id_pelaksana'),
                    'unit' => $this->input->post('unit'),
                    'tahun' => $this->input->post('tahun'),
                    'keterangan' => $this->input->post('keterangan'),
                    'last_update' => $this->input->post('last_update'),
                );

                $this->Perumahan__pembangunan_rumah_model->update_perumahan__pembangunan_rumah($id_pembangunan, $params);
                redirect('perumahan__pembangunan_rumah/index');
            } else {
                $this->load->model('Reg__village_model');
                $data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

                $this->load->model('Perumahan_dropdown__mbr_model');
                $data['all_perumahan_dropdown__mbr'] = $this->Perumahan_dropdown__mbr_model->get_all_perumahan_dropdown__mbr();

                $this->load->model('Perumahan_dropdown__imb_model');
                $data['all_perumahan_dropdown__imb'] = $this->Perumahan_dropdown__imb_model->get_all_perumahan_dropdown__imb();

                $this->load->model('Perumahan_dropdown__pelaksana_model');
                $data['all_perumahan_dropdown__pelaksana'] = $this->Perumahan_dropdown__pelaksana_model->get_all_perumahan_dropdown__pelaksana();

                $data['_view'] = 'perumahan__pembangunan_rumah/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The perumahan__pembangunan_rumah you are trying to edit does not exist.');
    }

    /*
     * Deleting perumahan__pembangunan_rumah
     */
    function remove($id_pembangunan)
    {
        $perumahan__pembangunan_rumah = $this->Perumahan__pembangunan_rumah_model->get_perumahan__pembangunan_rumah($id_pembangunan);

        // check if the perumahan__pembangunan_rumah exists before trying to delete it
        if (isset($perumahan__pembangunan_rumah['id_pembangunan'])) {
            $this->Perumahan__pembangunan_rumah_model->delete_perumahan__pembangunan_rumah($id_pembangunan);
            redirect('perumahan__pembangunan_rumah/index');
        } else
            show_error('The perumahan__pembangunan_rumah you are trying to delete does not exist.');
    }
}
