<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__pelaksana extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan_dropdown__pelaksana_model');
    } 

    /*
     * Listing of perumahan_dropdown__pelaksana
     */
    function index()
    {
        $data['perumahan_dropdown__pelaksana'] = $this->Perumahan_dropdown__pelaksana_model->get_all_perumahan_dropdown__pelaksana();
        
        $data['_view'] = 'perumahan_dropdown__pelaksana/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perumahan_dropdown__pelaksana
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pelaksana' => $this->input->post('pelaksana'),
            );
            
            $perumahan_dropdown__pelaksana_id = $this->Perumahan_dropdown__pelaksana_model->add_perumahan_dropdown__pelaksana($params);
            redirect('perumahan_dropdown__pelaksana/index');
        }
        else
        {            
            $data['_view'] = 'perumahan_dropdown__pelaksana/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perumahan_dropdown__pelaksana
     */
    function edit($id_pelaksana)
    {   
        // check if the perumahan_dropdown__pelaksana exists before trying to edit it
        $data['perumahan_dropdown__pelaksana'] = $this->Perumahan_dropdown__pelaksana_model->get_perumahan_dropdown__pelaksana($id_pelaksana);
        
        if(isset($data['perumahan_dropdown__pelaksana']['id_pelaksana']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pelaksana' => $this->input->post('pelaksana'),
                );

                $this->Perumahan_dropdown__pelaksana_model->update_perumahan_dropdown__pelaksana($id_pelaksana,$params);            
                redirect('perumahan_dropdown__pelaksana/index');
            }
            else
            {
                $data['_view'] = 'perumahan_dropdown__pelaksana/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perumahan_dropdown__pelaksana you are trying to edit does not exist.');
    } 

    /*
     * Deleting perumahan_dropdown__pelaksana
     */
    function remove($id_pelaksana)
    {
        $perumahan_dropdown__pelaksana = $this->Perumahan_dropdown__pelaksana_model->get_perumahan_dropdown__pelaksana($id_pelaksana);

        // check if the perumahan_dropdown__pelaksana exists before trying to delete it
        if(isset($perumahan_dropdown__pelaksana['id_pelaksana']))
        {
            $this->Perumahan_dropdown__pelaksana_model->delete_perumahan_dropdown__pelaksana($id_pelaksana);
            redirect('perumahan_dropdown__pelaksana/index');
        }
        else
            show_error('The perumahan_dropdown__pelaksana you are trying to delete does not exist.');
    }
    
}
