<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__mbr extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan_dropdown__mbr_model');
    } 

    /*
     * Listing of perumahan_dropdown__mbr
     */
    function index()
    {
        $data['perumahan_dropdown__mbr'] = $this->Perumahan_dropdown__mbr_model->get_all_perumahan_dropdown__mbr();
        
        $data['_view'] = 'perumahan_dropdown__mbr/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perumahan_dropdown__mbr
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'mbr' => $this->input->post('mbr'),
            );
            
            $perumahan_dropdown__mbr_id = $this->Perumahan_dropdown__mbr_model->add_perumahan_dropdown__mbr($params);
            redirect('perumahan_dropdown__mbr/index');
        }
        else
        {            
            $data['_view'] = 'perumahan_dropdown__mbr/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perumahan_dropdown__mbr
     */
    function edit($id_mbr)
    {   
        // check if the perumahan_dropdown__mbr exists before trying to edit it
        $data['perumahan_dropdown__mbr'] = $this->Perumahan_dropdown__mbr_model->get_perumahan_dropdown__mbr($id_mbr);
        
        if(isset($data['perumahan_dropdown__mbr']['id_mbr']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'mbr' => $this->input->post('mbr'),
                );

                $this->Perumahan_dropdown__mbr_model->update_perumahan_dropdown__mbr($id_mbr,$params);            
                redirect('perumahan_dropdown__mbr/index');
            }
            else
            {
                $data['_view'] = 'perumahan_dropdown__mbr/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perumahan_dropdown__mbr you are trying to edit does not exist.');
    } 

    /*
     * Deleting perumahan_dropdown__mbr
     */
    function remove($id_mbr)
    {
        $perumahan_dropdown__mbr = $this->Perumahan_dropdown__mbr_model->get_perumahan_dropdown__mbr($id_mbr);

        // check if the perumahan_dropdown__mbr exists before trying to delete it
        if(isset($perumahan_dropdown__mbr['id_mbr']))
        {
            $this->Perumahan_dropdown__mbr_model->delete_perumahan_dropdown__mbr($id_mbr);
            redirect('perumahan_dropdown__mbr/index');
        }
        else
            show_error('The perumahan_dropdown__mbr you are trying to delete does not exist.');
    }
    
}
