<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Perumahan__spm extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan__spm_model');
    }

    /*
     * Listing of perumahan__spm
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('perumahan__spm/index?');
        $config['total_rows'] = $this->Perumahan__spm_model->get_all_perumahan__spm_count();
        $this->pagination->initialize($config);

        $data['perumahan__spm'] = $this->Perumahan__spm_model->get_all_perumahan__spm($params);
        $data['title'] = "SPM";
        $data['_view'] = 'perumahan__spm/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new perumahan__spm
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'village_id' => $this->input->post('village_id'),
                'id_pekerjaan_spm' => $this->input->post('id_pekerjaan_spm'),
                'tahun' => $this->input->post('tahun'),
                'jml_rumah_ditangani' => $this->input->post('jml_rumah_ditangani'),
                'keterangan' => $this->input->post('keterangan'),
                'last_update' => $this->input->post('last_update'),
            );

            $perumahan__spm_id = $this->Perumahan__spm_model->add_perumahan__spm($params);
            redirect('perumahan__spm/index');
        } else {
            $this->load->model('Reg__village_model');
            $data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

            $this->load->model('Perumahan_dropdown__pekerjaan_spm_model');
            $data['all_perumahan_dropdown__pekerjaan_spm'] = $this->Perumahan_dropdown__pekerjaan_spm_model->get_all_perumahan_dropdown__pekerjaan_spm();

            $data['_view'] = 'perumahan__spm/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a perumahan__spm
     */
    function edit($id_spm)
    {
        // check if the perumahan__spm exists before trying to edit it
        $data['perumahan__spm'] = $this->Perumahan__spm_model->get_perumahan__spm($id_spm);

        if (isset($data['perumahan__spm']['id_spm'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'village_id' => $this->input->post('village_id'),
                    'id_pekerjaan_spm' => $this->input->post('id_pekerjaan_spm'),
                    'tahun' => $this->input->post('tahun'),
                    'jml_rumah_ditangani' => $this->input->post('jml_rumah_ditangani'),
                    'keterangan' => $this->input->post('keterangan'),
                    'last_update' => $this->input->post('last_update'),
                );

                $this->Perumahan__spm_model->update_perumahan__spm($id_spm, $params);
                redirect('perumahan__spm/index');
            } else {
                $this->load->model('Reg__village_model');
                $data['all_reg__villages'] = $this->Reg__village_model->get_all_reg__villages();

                $this->load->model('Perumahan_dropdown__pekerjaan_spm_model');
                $data['all_perumahan_dropdown__pekerjaan_spm'] = $this->Perumahan_dropdown__pekerjaan_spm_model->get_all_perumahan_dropdown__pekerjaan_spm();

                $data['_view'] = 'perumahan__spm/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The perumahan__spm you are trying to edit does not exist.');
    }

    /*
     * Deleting perumahan__spm
     */
    function remove($id_spm)
    {
        $perumahan__spm = $this->Perumahan__spm_model->get_perumahan__spm($id_spm);

        // check if the perumahan__spm exists before trying to delete it
        if (isset($perumahan__spm['id_spm'])) {
            $this->Perumahan__spm_model->delete_perumahan__spm($id_spm);
            redirect('perumahan__spm/index');
        } else
            show_error('The perumahan__spm you are trying to delete does not exist.');
    }
}
