<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan__backlog extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perumahan__backlog_model');
    } 

    /*
     * Listing of perumahan__backlog
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('perumahan__backlog/index?');
        $config['total_rows'] = $this->Perumahan__backlog_model->get_all_perumahan__backlog_count();
        $this->pagination->initialize($config);

        $data['perumahan__backlog'] = $this->Perumahan__backlog_model->get_all_perumahan__backlog($params);
        
        $data['_view'] = 'perumahan__backlog/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perumahan__backlog
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('backlog_kepemilikan','Backlog Kepemilikan','required|integer');
		$this->form_validation->set_rules('backlog_penghunian','Backlog Penghunian','required|integer');
		$this->form_validation->set_rules('tahun','Tahun','required|integer');
		$this->form_validation->set_rules('keterangan','Keterangan','required|max_length[100]');
		$this->form_validation->set_rules('last_update','Last Update','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'district_id' => $this->input->post('district_id'),
				'backlog_kepemilikan' => $this->input->post('backlog_kepemilikan'),
				'backlog_penghunian' => $this->input->post('backlog_penghunian'),
				'tahun' => $this->input->post('tahun'),
				'keterangan' => $this->input->post('keterangan'),
				'last_update' => $this->input->post('last_update'),
            );
            
            $perumahan__backlog_id = $this->Perumahan__backlog_model->add_perumahan__backlog($params);
            redirect('perumahan__backlog/index');
        }
        else
        {
			$this->load->model('Reg__district_model');
			$data['all_reg__districts'] = $this->Reg__district_model->get_all_reg__districts();
            
            $data['_view'] = 'perumahan__backlog/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perumahan__backlog
     */
    function edit($id_backlog)
    {   
        // check if the perumahan__backlog exists before trying to edit it
        $data['perumahan__backlog'] = $this->Perumahan__backlog_model->get_perumahan__backlog($id_backlog);
        
        if(isset($data['perumahan__backlog']['id_backlog']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('backlog_kepemilikan','Backlog Kepemilikan','required|integer');
			$this->form_validation->set_rules('backlog_penghunian','Backlog Penghunian','required|integer');
			$this->form_validation->set_rules('tahun','Tahun','required|integer');
			$this->form_validation->set_rules('keterangan','Keterangan','required|max_length[100]');
			$this->form_validation->set_rules('last_update','Last Update','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'district_id' => $this->input->post('district_id'),
					'backlog_kepemilikan' => $this->input->post('backlog_kepemilikan'),
					'backlog_penghunian' => $this->input->post('backlog_penghunian'),
					'tahun' => $this->input->post('tahun'),
					'keterangan' => $this->input->post('keterangan'),
					'last_update' => $this->input->post('last_update'),
                );

                $this->Perumahan__backlog_model->update_perumahan__backlog($id_backlog,$params);            
                redirect('perumahan__backlog/index');
            }
            else
            {
				$this->load->model('Reg__district_model');
				$data['all_reg__districts'] = $this->Reg__district_model->get_all_reg__districts();

                $data['_view'] = 'perumahan__backlog/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perumahan__backlog you are trying to edit does not exist.');
    } 

    /*
     * Deleting perumahan__backlog
     */
    function remove($id_backlog)
    {
        $perumahan__backlog = $this->Perumahan__backlog_model->get_perumahan__backlog($id_backlog);

        // check if the perumahan__backlog exists before trying to delete it
        if(isset($perumahan__backlog['id_backlog']))
        {
            $this->Perumahan__backlog_model->delete_perumahan__backlog($id_backlog);
            redirect('perumahan__backlog/index');
        }
        else
            show_error('The perumahan__backlog you are trying to delete does not exist.');
    }
    
}
