<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reg__village extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reg__village_model');
    } 

    /*
     * Listing of reg__villages
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('reg__village/index?');
        $config['total_rows'] = $this->Reg__village_model->get_all_reg__villages_count();
        $this->pagination->initialize($config);

        $data['reg__villages'] = $this->Reg__village_model->get_all_reg__villages($params);
        
        $data['_view'] = 'reg__village/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reg__village
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'district_id' => $this->input->post('district_id'),
				'name' => $this->input->post('name'),
            );
            
            $reg__village_id = $this->Reg__village_model->add_reg__village($params);
            redirect('reg__village/index');
        }
        else
        {            
            $data['_view'] = 'reg__village/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reg__village
     */
    function edit($id)
    {   
        // check if the reg__village exists before trying to edit it
        $data['reg__village'] = $this->Reg__village_model->get_reg__village($id);
        
        if(isset($data['reg__village']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'district_id' => $this->input->post('district_id'),
					'name' => $this->input->post('name'),
                );

                $this->Reg__village_model->update_reg__village($id,$params);            
                redirect('reg__village/index');
            }
            else
            {
                $data['_view'] = 'reg__village/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reg__village you are trying to edit does not exist.');
    } 

    /*
     * Deleting reg__village
     */
    function remove($id)
    {
        $reg__village = $this->Reg__village_model->get_reg__village($id);

        // check if the reg__village exists before trying to delete it
        if(isset($reg__village['id']))
        {
            $this->Reg__village_model->delete_reg__village($id);
            redirect('reg__village/index');
        }
        else
            show_error('The reg__village you are trying to delete does not exist.');
    }
    
}
