<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reg__regency extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reg__regency_model');
    } 

    /*
     * Listing of reg__regencies
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('reg__regency/index?');
        $config['total_rows'] = $this->Reg__regency_model->get_all_reg__regencies_count();
        $this->pagination->initialize($config);

        $data['reg__regencies'] = $this->Reg__regency_model->get_all_reg__regencies($params);
        
        $data['_view'] = 'reg__regency/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reg__regency
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'province_id' => $this->input->post('province_id'),
				'name' => $this->input->post('name'),
            );
            
            $reg__regency_id = $this->Reg__regency_model->add_reg__regency($params);
            redirect('reg__regency/index');
        }
        else
        {            
            $data['_view'] = 'reg__regency/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reg__regency
     */
    function edit($id)
    {   
        // check if the reg__regency exists before trying to edit it
        $data['reg__regency'] = $this->Reg__regency_model->get_reg__regency($id);
        
        if(isset($data['reg__regency']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'province_id' => $this->input->post('province_id'),
					'name' => $this->input->post('name'),
                );

                $this->Reg__regency_model->update_reg__regency($id,$params);            
                redirect('reg__regency/index');
            }
            else
            {
                $data['_view'] = 'reg__regency/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reg__regency you are trying to edit does not exist.');
    } 

    /*
     * Deleting reg__regency
     */
    function remove($id)
    {
        $reg__regency = $this->Reg__regency_model->get_reg__regency($id);

        // check if the reg__regency exists before trying to delete it
        if(isset($reg__regency['id']))
        {
            $this->Reg__regency_model->delete_reg__regency($id);
            redirect('reg__regency/index');
        }
        else
            show_error('The reg__regency you are trying to delete does not exist.');
    }
    
}
