<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_menu_model');
    } 

    /*
     * Listing of user_menu
     */
    function index()
    {
        $data['user_menu'] = $this->User_menu_model->get_all_user_menu();
        
        $data['_view'] = 'user_menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'menu' => $this->input->post('menu'),
            );
            
            $user_menu_id = $this->User_menu_model->add_user_menu($params);
            redirect('user_menu/index');
        }
        else
        {            
            $data['_view'] = 'user_menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_menu
     */
    function edit($id)
    {   
        // check if the user_menu exists before trying to edit it
        $data['user_menu'] = $this->User_menu_model->get_user_menu($id);
        
        if(isset($data['user_menu']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'menu' => $this->input->post('menu'),
                );

                $this->User_menu_model->update_user_menu($id,$params);            
                redirect('user_menu/index');
            }
            else
            {
                $data['_view'] = 'user_menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_menu
     */
    function remove($id)
    {
        $user_menu = $this->User_menu_model->get_user_menu($id);

        // check if the user_menu exists before trying to delete it
        if(isset($user_menu['id']))
        {
            $this->User_menu_model->delete_user_menu($id);
            redirect('user_menu/index');
        }
        else
            show_error('The user_menu you are trying to delete does not exist.');
    }
    
}
