<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_sub_menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_sub_menu_model');
    } 

    /*
     * Listing of user_sub_menu
     */
    function index()
    {
        $data['user_sub_menu'] = $this->User_sub_menu_model->get_all_user_sub_menu();
        
        $data['_view'] = 'user_sub_menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_sub_menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'menu_id' => $this->input->post('menu_id'),
				'title' => $this->input->post('title'),
				'url' => $this->input->post('url'),
				'icon' => $this->input->post('icon'),
				'is_active' => $this->input->post('is_active'),
            );
            
            $user_sub_menu_id = $this->User_sub_menu_model->add_user_sub_menu($params);
            redirect('user_sub_menu/index');
        }
        else
        {            
            $data['_view'] = 'user_sub_menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_sub_menu
     */
    function edit($id)
    {   
        // check if the user_sub_menu exists before trying to edit it
        $data['user_sub_menu'] = $this->User_sub_menu_model->get_user_sub_menu($id);
        
        if(isset($data['user_sub_menu']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'menu_id' => $this->input->post('menu_id'),
					'title' => $this->input->post('title'),
					'url' => $this->input->post('url'),
					'icon' => $this->input->post('icon'),
					'is_active' => $this->input->post('is_active'),
                );

                $this->User_sub_menu_model->update_user_sub_menu($id,$params);            
                redirect('user_sub_menu/index');
            }
            else
            {
                $data['_view'] = 'user_sub_menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_sub_menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_sub_menu
     */
    function remove($id)
    {
        $user_sub_menu = $this->User_sub_menu_model->get_user_sub_menu($id);

        // check if the user_sub_menu exists before trying to delete it
        if(isset($user_sub_menu['id']))
        {
            $this->User_sub_menu_model->delete_user_sub_menu($id);
            redirect('user_sub_menu/index');
        }
        else
            show_error('The user_sub_menu you are trying to delete does not exist.');
    }
    
}
