<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan_dropdown__tingkat_kumuh_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kawasan_dropdown__tingkat_kumuh by id_tk
     */
    function get_kawasan_dropdown__tingkat_kumuh($id_tk)
    {
        return $this->db->get_where('kawasan_dropdown__tingkat_kumuh',array('id_tk'=>$id_tk))->row_array();
    }
        
    /*
     * Get all kawasan_dropdown__tingkat_kumuh
     */
    function get_all_kawasan_dropdown__tingkat_kumuh()
    {
        $this->db->order_by('id_tk', 'desc');
        return $this->db->get('kawasan_dropdown__tingkat_kumuh')->result_array();
    }
        
    /*
     * function to add new kawasan_dropdown__tingkat_kumuh
     */
    function add_kawasan_dropdown__tingkat_kumuh($params)
    {
        $this->db->insert('kawasan_dropdown__tingkat_kumuh',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kawasan_dropdown__tingkat_kumuh
     */
    function update_kawasan_dropdown__tingkat_kumuh($id_tk,$params)
    {
        $this->db->where('id_tk',$id_tk);
        return $this->db->update('kawasan_dropdown__tingkat_kumuh',$params);
    }
    
    /*
     * function to delete kawasan_dropdown__tingkat_kumuh
     */
    function delete_kawasan_dropdown__tingkat_kumuh($id_tk)
    {
        return $this->db->delete('kawasan_dropdown__tingkat_kumuh',array('id_tk'=>$id_tk));
    }
}
