<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan__lokasi_kumuh_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kawasan__lokasi_kumuh by id_lokasi
     */
    function get_kawasan__lokasi_kumuh($id_lokasi)
    {
        return $this->db->get_where('kawasan__lokasi_kumuh',array('id_lokasi'=>$id_lokasi))->row_array();
    }
    
    /*
     * Get all kawasan__lokasi_kumuh count
     */
    function get_all_kawasan__lokasi_kumuh_count()
    {
        $this->db->from('kawasan__lokasi_kumuh');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all kawasan__lokasi_kumuh
     */
    function get_all_kawasan__lokasi_kumuh($params = array())
    {
        $this->db->order_by('id_lokasi', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('kawasan__lokasi_kumuh')->result_array();
    }
        
    /*
     * function to add new kawasan__lokasi_kumuh
     */
    function add_kawasan__lokasi_kumuh($params)
    {
        $this->db->insert('kawasan__lokasi_kumuh',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kawasan__lokasi_kumuh
     */
    function update_kawasan__lokasi_kumuh($id_lokasi,$params)
    {
        $this->db->where('id_lokasi',$id_lokasi);
        return $this->db->update('kawasan__lokasi_kumuh',$params);
    }
    
    /*
     * function to delete kawasan__lokasi_kumuh
     */
    function delete_kawasan__lokasi_kumuh($id_lokasi)
    {
        return $this->db->delete('kawasan__lokasi_kumuh',array('id_lokasi'=>$id_lokasi));
    }
}
