<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan__penanganan_lokasi_kumuh_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kawasan__penanganan_lokasi_kumuh by id_penanganan
     */
    function get_kawasan__penanganan_lokasi_kumuh($id_penanganan)
    {
        return $this->db->get_where('kawasan__penanganan_lokasi_kumuh',array('id_penanganan'=>$id_penanganan))->row_array();
    }
    
    /*
     * Get all kawasan__penanganan_lokasi_kumuh count
     */
    function get_all_kawasan__penanganan_lokasi_kumuh_count()
    {
        $this->db->from('kawasan__penanganan_lokasi_kumuh');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all kawasan__penanganan_lokasi_kumuh
     */
    function get_all_kawasan__penanganan_lokasi_kumuh($params = array())
    {
        $this->db->order_by('id_penanganan', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('kawasan__penanganan_lokasi_kumuh')->result_array();
    }
        
    /*
     * function to add new kawasan__penanganan_lokasi_kumuh
     */
    function add_kawasan__penanganan_lokasi_kumuh($params)
    {
        $this->db->insert('kawasan__penanganan_lokasi_kumuh',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kawasan__penanganan_lokasi_kumuh
     */
    function update_kawasan__penanganan_lokasi_kumuh($id_penanganan,$params)
    {
        $this->db->where('id_penanganan',$id_penanganan);
        return $this->db->update('kawasan__penanganan_lokasi_kumuh',$params);
    }
    
    /*
     * function to delete kawasan__penanganan_lokasi_kumuh
     */
    function delete_kawasan__penanganan_lokasi_kumuh($id_penanganan)
    {
        return $this->db->delete('kawasan__penanganan_lokasi_kumuh',array('id_penanganan'=>$id_penanganan));
    }
}
