<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kawasan__surat_keterangan_kumuh_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kawasan__surat_keterangan_kumuh by id_sk
     */
    function get_kawasan__surat_keterangan_kumuh($id_sk)
    {
        return $this->db->get_where('kawasan__surat_keterangan_kumuh',array('id_sk'=>$id_sk))->row_array();
    }
    
    /*
     * Get all kawasan__surat_keterangan_kumuh count
     */
    function get_all_kawasan__surat_keterangan_kumuh_count()
    {
        $this->db->from('kawasan__surat_keterangan_kumuh');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all kawasan__surat_keterangan_kumuh
     */
    function get_all_kawasan__surat_keterangan_kumuh($params = array())
    {
        $this->db->order_by('id_sk', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('kawasan__surat_keterangan_kumuh')->result_array();
    }
        
    /*
     * function to add new kawasan__surat_keterangan_kumuh
     */
    function add_kawasan__surat_keterangan_kumuh($params)
    {
        $this->db->insert('kawasan__surat_keterangan_kumuh',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kawasan__surat_keterangan_kumuh
     */
    function update_kawasan__surat_keterangan_kumuh($id_sk,$params)
    {
        $this->db->where('id_sk',$id_sk);
        return $this->db->update('kawasan__surat_keterangan_kumuh',$params);
    }
    
    /*
     * function to delete kawasan__surat_keterangan_kumuh
     */
    function delete_kawasan__surat_keterangan_kumuh($id_sk)
    {
        return $this->db->delete('kawasan__surat_keterangan_kumuh',array('id_sk'=>$id_sk));
    }
}
