<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan__spm_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan__spm by id_spm
     */
    function get_perumahan__spm($id_spm)
    {
        return $this->db->get_where('perumahan__spm',array('id_spm'=>$id_spm))->row_array();
    }
    
    /*
     * Get all perumahan__spm count
     */
    function get_all_perumahan__spm_count()
    {
        $this->db->from('perumahan__spm');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all perumahan__spm
     */
    function get_all_perumahan__spm($params = array())
    {
        $this->db->order_by('id_spm', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('perumahan__spm')->result_array();
    }
        
    /*
     * function to add new perumahan__spm
     */
    function add_perumahan__spm($params)
    {
        $this->db->insert('perumahan__spm',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan__spm
     */
    function update_perumahan__spm($id_spm,$params)
    {
        $this->db->where('id_spm',$id_spm);
        return $this->db->update('perumahan__spm',$params);
    }
    
    /*
     * function to delete perumahan__spm
     */
    function delete_perumahan__spm($id_spm)
    {
        return $this->db->delete('perumahan__spm',array('id_spm'=>$id_spm));
    }
}
