<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan__kepemilikan_rumah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan__kepemilikan_rumah by id_kepemilikan
     */
    function get_perumahan__kepemilikan_rumah($id_kepemilikan)
    {
        return $this->db->get_where('perumahan__kepemilikan_rumah',array('id_kepemilikan'=>$id_kepemilikan))->row_array();
    }
    
    /*
     * Get all perumahan__kepemilikan_rumah count
     */
    function get_all_perumahan__kepemilikan_rumah_count()
    {
        $this->db->from('perumahan__kepemilikan_rumah');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all perumahan__kepemilikan_rumah
     */
    function get_all_perumahan__kepemilikan_rumah($params = array())
    {
        $this->db->order_by('id_kepemilikan', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('perumahan__kepemilikan_rumah')->result_array();
    }
        
    /*
     * function to add new perumahan__kepemilikan_rumah
     */
    function add_perumahan__kepemilikan_rumah($params)
    {
        $this->db->insert('perumahan__kepemilikan_rumah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan__kepemilikan_rumah
     */
    function update_perumahan__kepemilikan_rumah($id_kepemilikan,$params)
    {
        $this->db->where('id_kepemilikan',$id_kepemilikan);
        return $this->db->update('perumahan__kepemilikan_rumah',$params);
    }
    
    /*
     * function to delete perumahan__kepemilikan_rumah
     */
    function delete_perumahan__kepemilikan_rumah($id_kepemilikan)
    {
        return $this->db->delete('perumahan__kepemilikan_rumah',array('id_kepemilikan'=>$id_kepemilikan));
    }
}
