<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__pekerjaan_spm_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan_dropdown__pekerjaan_spm by id_pekerjaan_spm
     */
    function get_perumahan_dropdown__pekerjaan_spm($id_pekerjaan_spm)
    {
        return $this->db->get_where('perumahan_dropdown__pekerjaan_spm',array('id_pekerjaan_spm'=>$id_pekerjaan_spm))->row_array();
    }
        
    /*
     * Get all perumahan_dropdown__pekerjaan_spm
     */
    function get_all_perumahan_dropdown__pekerjaan_spm()
    {
        $this->db->order_by('id_pekerjaan_spm', 'desc');
        return $this->db->get('perumahan_dropdown__pekerjaan_spm')->result_array();
    }
        
    /*
     * function to add new perumahan_dropdown__pekerjaan_spm
     */
    function add_perumahan_dropdown__pekerjaan_spm($params)
    {
        $this->db->insert('perumahan_dropdown__pekerjaan_spm',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan_dropdown__pekerjaan_spm
     */
    function update_perumahan_dropdown__pekerjaan_spm($id_pekerjaan_spm,$params)
    {
        $this->db->where('id_pekerjaan_spm',$id_pekerjaan_spm);
        return $this->db->update('perumahan_dropdown__pekerjaan_spm',$params);
    }
    
    /*
     * function to delete perumahan_dropdown__pekerjaan_spm
     */
    function delete_perumahan_dropdown__pekerjaan_spm($id_pekerjaan_spm)
    {
        return $this->db->delete('perumahan_dropdown__pekerjaan_spm',array('id_pekerjaan_spm'=>$id_pekerjaan_spm));
    }
}
