<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__mbr_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan_dropdown__mbr by id_mbr
     */
    function get_perumahan_dropdown__mbr($id_mbr)
    {
        return $this->db->get_where('perumahan_dropdown__mbr',array('id_mbr'=>$id_mbr))->row_array();
    }
        
    /*
     * Get all perumahan_dropdown__mbr
     */
    function get_all_perumahan_dropdown__mbr()
    {
        $this->db->order_by('id_mbr', 'desc');
        return $this->db->get('perumahan_dropdown__mbr')->result_array();
    }
        
    /*
     * function to add new perumahan_dropdown__mbr
     */
    function add_perumahan_dropdown__mbr($params)
    {
        $this->db->insert('perumahan_dropdown__mbr',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan_dropdown__mbr
     */
    function update_perumahan_dropdown__mbr($id_mbr,$params)
    {
        $this->db->where('id_mbr',$id_mbr);
        return $this->db->update('perumahan_dropdown__mbr',$params);
    }
    
    /*
     * function to delete perumahan_dropdown__mbr
     */
    function delete_perumahan_dropdown__mbr($id_mbr)
    {
        return $this->db->delete('perumahan_dropdown__mbr',array('id_mbr'=>$id_mbr));
    }
}
