<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__pelaksana_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan_dropdown__pelaksana by id_pelaksana
     */
    function get_perumahan_dropdown__pelaksana($id_pelaksana)
    {
        return $this->db->get_where('perumahan_dropdown__pelaksana',array('id_pelaksana'=>$id_pelaksana))->row_array();
    }
        
    /*
     * Get all perumahan_dropdown__pelaksana
     */
    function get_all_perumahan_dropdown__pelaksana()
    {
        $this->db->order_by('id_pelaksana', 'desc');
        return $this->db->get('perumahan_dropdown__pelaksana')->result_array();
    }
        
    /*
     * function to add new perumahan_dropdown__pelaksana
     */
    function add_perumahan_dropdown__pelaksana($params)
    {
        $this->db->insert('perumahan_dropdown__pelaksana',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan_dropdown__pelaksana
     */
    function update_perumahan_dropdown__pelaksana($id_pelaksana,$params)
    {
        $this->db->where('id_pelaksana',$id_pelaksana);
        return $this->db->update('perumahan_dropdown__pelaksana',$params);
    }
    
    /*
     * function to delete perumahan_dropdown__pelaksana
     */
    function delete_perumahan_dropdown__pelaksana($id_pelaksana)
    {
        return $this->db->delete('perumahan_dropdown__pelaksana',array('id_pelaksana'=>$id_pelaksana));
    }
}
