<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan__backlog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan__backlog by id_backlog
     */
    function get_perumahan__backlog($id_backlog)
    {
        return $this->db->get_where('perumahan__backlog',array('id_backlog'=>$id_backlog))->row_array();
    }
    
    /*
     * Get all perumahan__backlog count
     */
    function get_all_perumahan__backlog_count()
    {
        $this->db->from('perumahan__backlog');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all perumahan__backlog
     */
    function get_all_perumahan__backlog($params = array())
    {
        $this->db->order_by('id_backlog', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('perumahan__backlog')->result_array();
    }
        
    /*
     * function to add new perumahan__backlog
     */
    function add_perumahan__backlog($params)
    {
        $this->db->insert('perumahan__backlog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan__backlog
     */
    function update_perumahan__backlog($id_backlog,$params)
    {
        $this->db->where('id_backlog',$id_backlog);
        return $this->db->update('perumahan__backlog',$params);
    }
    
    /*
     * function to delete perumahan__backlog
     */
    function delete_perumahan__backlog($id_backlog)
    {
        return $this->db->delete('perumahan__backlog',array('id_backlog'=>$id_backlog));
    }
}
