<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan__pembangunan_rumah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan__pembangunan_rumah by id_pembangunan
     */
    function get_perumahan__pembangunan_rumah($id_pembangunan)
    {
        return $this->db->get_where('perumahan__pembangunan_rumah',array('id_pembangunan'=>$id_pembangunan))->row_array();
    }
    
    /*
     * Get all perumahan__pembangunan_rumah count
     */
    function get_all_perumahan__pembangunan_rumah_count()
    {
        $this->db->from('perumahan__pembangunan_rumah');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all perumahan__pembangunan_rumah
     */
    function get_all_perumahan__pembangunan_rumah($params = array())
    {
        $this->db->order_by('id_pembangunan', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('perumahan__pembangunan_rumah')->result_array();
    }
        
    /*
     * function to add new perumahan__pembangunan_rumah
     */
    function add_perumahan__pembangunan_rumah($params)
    {
        $this->db->insert('perumahan__pembangunan_rumah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan__pembangunan_rumah
     */
    function update_perumahan__pembangunan_rumah($id_pembangunan,$params)
    {
        $this->db->where('id_pembangunan',$id_pembangunan);
        return $this->db->update('perumahan__pembangunan_rumah',$params);
    }
    
    /*
     * function to delete perumahan__pembangunan_rumah
     */
    function delete_perumahan__pembangunan_rumah($id_pembangunan)
    {
        return $this->db->delete('perumahan__pembangunan_rumah',array('id_pembangunan'=>$id_pembangunan));
    }
}
