<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan__rtlh_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan__rtlh by id_rtlh
     */
    function get_perumahan__rtlh($id_rtlh)
    {
        return $this->db->get_where('perumahan__rtlh',array('id_rtlh'=>$id_rtlh))->row_array();
    }
    
    /*
     * Get all perumahan__rtlh count
     */
    function get_all_perumahan__rtlh_count()
    {
        $this->db->from('perumahan__rtlh');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all perumahan__rtlh
     */
    function get_all_perumahan__rtlh($params = array())
    {
        $this->db->order_by('id_rtlh', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('perumahan__rtlh')->result_array();
    }
        
    /*
     * function to add new perumahan__rtlh
     */
    function add_perumahan__rtlh($params)
    {
        $this->db->insert('perumahan__rtlh',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan__rtlh
     */
    function update_perumahan__rtlh($id_rtlh,$params)
    {
        $this->db->where('id_rtlh',$id_rtlh);
        return $this->db->update('perumahan__rtlh',$params);
    }
    
    /*
     * function to delete perumahan__rtlh
     */
    function delete_perumahan__rtlh($id_rtlh)
    {
        return $this->db->delete('perumahan__rtlh',array('id_rtlh'=>$id_rtlh));
    }
}
