<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perumahan_dropdown__imb_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perumahan_dropdown__imb by id_imb
     */
    function get_perumahan_dropdown__imb($id_imb)
    {
        return $this->db->get_where('perumahan_dropdown__imb',array('id_imb'=>$id_imb))->row_array();
    }
        
    /*
     * Get all perumahan_dropdown__imb
     */
    function get_all_perumahan_dropdown__imb()
    {
        $this->db->order_by('id_imb', 'desc');
        return $this->db->get('perumahan_dropdown__imb')->result_array();
    }
        
    /*
     * function to add new perumahan_dropdown__imb
     */
    function add_perumahan_dropdown__imb($params)
    {
        $this->db->insert('perumahan_dropdown__imb',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perumahan_dropdown__imb
     */
    function update_perumahan_dropdown__imb($id_imb,$params)
    {
        $this->db->where('id_imb',$id_imb);
        return $this->db->update('perumahan_dropdown__imb',$params);
    }
    
    /*
     * function to delete perumahan_dropdown__imb
     */
    function delete_perumahan_dropdown__imb($id_imb)
    {
        return $this->db->delete('perumahan_dropdown__imb',array('id_imb'=>$id_imb));
    }
}
