<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reg__province_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reg__province by id
     */
    function get_reg__province($id)
    {
        return $this->db->get_where('reg__provinces',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all reg__provinces count
     */
    function get_all_reg__provinces_count()
    {
        $this->db->from('reg__provinces');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all reg__provinces
     */
    function get_all_reg__provinces($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('reg__provinces')->result_array();
    }
        
    /*
     * function to add new reg__province
     */
    function add_reg__province($params)
    {
        $this->db->insert('reg__provinces',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reg__province
     */
    function update_reg__province($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('reg__provinces',$params);
    }
    
    /*
     * function to delete reg__province
     */
    function delete_reg__province($id)
    {
        return $this->db->delete('reg__provinces',array('id'=>$id));
    }
}
