<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reg__village_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reg__village by id
     */
    function get_reg__village($id)
    {
        return $this->db->get_where('reg__villages',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all reg__villages count
     */
    function get_all_reg__villages_count()
    {
        $this->db->from('reg__villages');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all reg__villages
     */
    function get_all_reg__villages($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('reg__villages')->result_array();
    }
        
    /*
     * function to add new reg__village
     */
    function add_reg__village($params)
    {
        $this->db->insert('reg__villages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reg__village
     */
    function update_reg__village($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('reg__villages',$params);
    }
    
    /*
     * function to delete reg__village
     */
    function delete_reg__village($id)
    {
        return $this->db->delete('reg__villages',array('id'=>$id));
    }
}
