<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reg__regency_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reg__regency by id
     */
    function get_reg__regency($id)
    {
        return $this->db->get_where('reg__regencies',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all reg__regencies count
     */
    function get_all_reg__regencies_count()
    {
        $this->db->from('reg__regencies');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all reg__regencies
     */
    function get_all_reg__regencies($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('reg__regencies')->result_array();
    }
        
    /*
     * function to add new reg__regency
     */
    function add_reg__regency($params)
    {
        $this->db->insert('reg__regencies',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reg__regency
     */
    function update_reg__regency($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('reg__regencies',$params);
    }
    
    /*
     * function to delete reg__regency
     */
    function delete_reg__regency($id)
    {
        return $this->db->delete('reg__regencies',array('id'=>$id));
    }
}
