<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_access_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_access_menu by id
     */
    function get_user_access_menu($id)
    {
        return $this->db->get_where('user_access_menu',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all user_access_menu count
     */
    function get_all_user_access_menu_count()
    {
        $this->db->from('user_access_menu');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all user_access_menu
     */
    function get_all_user_access_menu($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('user_access_menu')->result_array();
    }
        
    /*
     * function to add new user_access_menu
     */
    function add_user_access_menu($params)
    {
        $this->db->insert('user_access_menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_access_menu
     */
    function update_user_access_menu($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_access_menu',$params);
    }
    
    /*
     * function to delete user_access_menu
     */
    function delete_user_access_menu($id)
    {
        return $this->db->delete('user_access_menu',array('id'=>$id));
    }
}
