<?php
$config['pagination']['page_query_string'] = TRUE;
$config['pagination']['uri_segment'] = 3;

$config['pagination']['per_page'] = RECORDS_PER_PAGE;

// $config['pagination']['prev_link'] = '‹';
// $config['pagination']['next_link'] = '›';
// $config['pagination']['full_tag_open'] = '<ul class="pagination">';
// $config['pagination']['next_tag_open'] = '<li>';
// $config['pagination']['next_tag_close'] = '</li>';
// $config['pagination']['prev_tag_open'] = '<li>';
// $config['pagination']['prev_tag_close'] = '</li>';
// $config['pagination']['num_tag_open'] = '<li>';
// $config['pagination']['num_tag_close'] = '</li>';
// $config['pagination']['cur_tag_open'] = '<li class="active"><a href="">';
// $config['pagination']['cur_tag_close'] = '</a></li>';
// $config['pagination']['full_tag_close'] = '</ul>';
// $config['pagination']['first_link'] = '‹‹';
// $config['pagination']['first_tag_open'] = '<li>';
// $config['pagination']['first_tag_close'] = '</li>';
// $config['pagination']['last_link'] = '››';
// $config['pagination']['last_tag_open'] = '<li>';
// $config['pagination']['last_tag_close'] = '</li>';
$config['pagination']['full_tag_open'] = '<nav><ul class="pagination">';
$config['pagination']['full_tag_close'] = '</ul></nav>';
$config['pagination']['next_link'] = '&raquo';
$config['pagination']['next_tag_open'] = '<li class="page-item">';
$config['pagination']['next_tag_close'] = '</li>';
$config['pagination']['prev_link'] = '&laquo';
$config['pagination']['prev_tag_open'] = '<li class="page-item">';
$config['pagination']['prev_tag_close'] = '</li>';
$config['pagination']['first_tag_open'] = '<li class="page-item">';
$config['pagination']['first_tag_close'] = '</li>';
$config['pagination']['last_tag_open'] = '<li class="page-item">';
$config['pagination']['last_tag_close'] = '</li>';
$config['pagination']['cur_tag_open'] = '<li class="page-item active"><a class="page-link" href="#">';
$config['pagination']['cur_tag_close'] = '<span class="sr-only">(current)</span></a></li>';
$config['pagination']['num_tag_open'] = '<li class="page-item">';
$config['pagination']['num_tag_close'] = '</li>';
$config['pagination']['attributes'] = array('class' => 'page-link');
